task 1 done
alvls/mp1-2024-1 pull request #13
Opened 2024-02-25 22:05 UTC by smallAbyss

2024-03-03 16:15 UTC, smallAbyss commented
Следующие комиты относятся к task2

2024-03-07 14:44 UTC, alvls requested changes

2024-03-07 14:44 UTC, alvls commented on Luzan_EA/task2/Vect.h
> +vect operator* (vect v_l, vect v_r);
В операциях есть несколько вариантов умножения, но нет того, что требовался - скалярного произведения.

2024-03-07 14:44 UTC, alvls commented on Luzan_EA/task2/Vect.cpp
> +        cout << "Warning! Size must be less than 21, size reduced to 20\n";
Здесь и далее не нужно ничего выводить на консоль. Ее может не быть. И это может помешать организации интерфейса.

2024-03-07 14:45 UTC, alvls commented
Егор, в проект task1 нужно добавить ваш исходник.
По проекту task2 исправить замечания.

2024-03-07 18:11 UTC, smallAbyss commented on Luzan_EA/task2/Vect.h
> +vect operator* (vect v_l, vect v_r);
Да, увлёкся написанием сложений.  Исправил, операцию «*=» убрал, так как она теперь не имеет смысла. Умножение занёс обратно в класс. Изначально хотел объединить умножение константы на вектор и вектора на вектор, уже тогда это было плохой идеей, а сейчас просто бред

2024-03-07 18:18 UTC, smallAbyss commented
Не совсем понял, что нужно было сделать с task1, но, кажется, это мне не помешало. 

Замечания по task2 исправил

2024-03-07 20:16 UTC, smallAbyss commented on Luzan_EA/task2/Vect.cpp
> +        cout << "Warning! Size must be less than 21, size reduced to 20\n";
Исправил

2024-03-10 13:59 UTC, alvls commented
По заданию 1.

Идея с тестами хороша, но они не должны быть публичными методами класса, который тестируют, а лучше вообще не должны быть методами. Один из вариантов - создать отдельный класс для тестирования нужного класса и сделать его дружественным.

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2024-03-10 14:06 UTC, alvls commented
По заданию 2.

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2024-03-10 14:06 UTC, merged