task 3
alvls/mp1-2024-1 pull request #19
Opened 2024-03-15 09:05 UTC by elus10n

2024-05-17 13:33 UTC, alvls commented on lukin.ia/task5/task5.cpp
> +	static processing_center clients; //���������� ���� ���� ������ �� ��� ��������� ����� ����� (�������)
Технически вариант рабочий. Действительно, будет один процессинговый центр на все банкоматы, но есть нюанс. static-поля это по сути глобальные переменные с точки зрения времени жизни и размещения. То есть, неважно, как и в какой момент в программе будут создаваться банкоматы, ПЦ должен быть создан еще до main и будет удален по ее завершении. Это существенное ограничение. Есть более удобный вариант такой связи: указатель или ссылка.

2024-05-17 13:36 UTC, elus10n commented on lukin.ia/task5/task5.cpp
> +	static processing_center clients; //���������� ���� ���� ������ �� ��� ��������� ����� ����� (�������)
Хорошо, исправлю на указатель

2024-05-17 13:45 UTC, alvls requested changes

2024-05-17 13:45 UTC, alvls commented on lukin.ia/task3/task3.cpp
> +		return tmp;
Реализация не верная. Требовалось ограничить вводимую пользователем строку установленным числом символов. А у вас можно ввести сколько угодно символов, после чего вы введенную строку обрезаете. Нужно переделать.

2024-05-17 13:51 UTC, elus10n commented on lukin.ia/task3/task3.cpp
> +		return tmp;
В текстовом редакторе предполагается вывод на экран, или лучше не надо?

2024-05-17 14:07 UTC, alvls commented on lukin.ia/task3/task3.cpp
> +		return tmp;
Вывод на экран происходит в процессе ввода. Если вы про еще один вывод, то нет, не предполагается.

2024-05-17 14:19 UTC, alvls commented
В ЛР5 теперь ОК. В ЛР3 снова неверно. Если задана длина поля ввода в 10 символов, то редактор не должен позволять вводить ничего после 10-го символа, только стирать предыдущие.

2024-05-20 09:08 UTC, alvls commented
По ЛР3

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2024-05-20 09:09 UTC, alvls commented
По ЛР4

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,1
Штраф: | 0,0
__Итого:__ | 8,1

2024-05-20 09:10 UTC, alvls commented
По ЛР5

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 5,0
Качество   проектирования: | 2,5
Качество кода: | 2,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 10,0

2024-05-21 11:13 UTC, merged