Complete task 3
alvls/mp1-2024-1 pull request #20
Opened 2024-03-15 09:27 UTC by H1nkk

2024-04-01 10:15 UTC, H1nkk commented
Тестовый файл: [test.txt](https://github.com/alvls/mp1-2024-1/files/14822413/test.txt)

2024-05-20 09:49 UTC, alvls requested changes

2024-05-20 09:49 UTC, alvls commented on Zavyalov_AA/task3/slte.h
> +		delete[] buffer;
Реализация неверная. Требовалось ограничить вводимую пользователем строку установленным числом символов. А у вас можно ввести сколько угодно символов. Введенная строка, конечно, обрезается, но этого недостаточно. Нужно переделать.

2024-05-20 09:52 UTC, alvls commented on Zavyalov_AA/task4/FilmLibrary.h
> +    set<Film, bool (*)(const Film&, const Film&)> films_by_fees{ compareFilmsByFees };
Идея любопытная, но не додумано до конца. Проблема в том, что у вас в результате каждый фильм хранится в трех копиях в трех контейнерах.

2024-05-20 09:52 UTC, alvls commented on Zavyalov_AA/task4/FilmLibrary.cpp
> +	}
Во всех операциях, где есть поиск фильма тот факт, что фильмы храняться упорядоченно, не используется.

2024-05-20 09:58 UTC, alvls commented
По ЛР5

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 5,0
Качество   проектирования: | 2,5
Качество кода: | 2,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 10,0

2024-05-22 13:38 UTC, alvls commented
По ЛР3

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество   кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2024-05-22 13:42 UTC, alvls commented
По ЛР4. Поиск исправили. Тройное хранение фильмов так и осталось.

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 1,2
Качество   кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 7,2

2024-05-25 16:07 UTC, alvls commented
По ЛР6

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 8,0
Качество   проектирования: | 3,5
Качество   кода: | 3,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 15,0

2024-05-25 16:09 UTC, merged