class Taylor_Series developed
alvls/mp1-2024-1 pull request #21
Opened 2024-03-15 10:54 UTC by VALancaster

Программа написана в Xcode на MacOS. Писать в VSCode возможности нет.

2024-05-17 12:16 UTC, VALancaster commented
перепутал task5 и task6. Не к тому заданию в результате приложил код. Попробую поменять местами приложенные программы.

2024-05-20 18:37 UTC, alvls requested changes

2024-05-20 18:37 UTC, alvls commented on kutergin_vt/task5/file_credit.h
> +    void payOffCredit(int acc_num, Processing_Center& obj); // функция, досрочно погашающая кредит
Поскольку вы передаете ссылку на Processing_Center в каждый метод, получается, что в каждый метод может прийти разный ПЦ. То есть авторизация может быть в одном ПЦ, а другая операция в другом. Подумайте, как исправить.

2024-05-20 19:06 UTC, alvls commented
По ЛР3

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2024-05-20 19:06 UTC, alvls commented
По ЛР4

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2024-05-22 09:32 UTC, alvls commented
По ЛР5

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 5,0
Качество   проектирования: | 2,5
Качество   кода: | 2,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 10,0

2024-05-26 18:31 UTC, alvls commented on kutergin_vt/task6/main.cpp
> +            } while (snake.isInsideBody(foodX, foodY)); // пока фрукт спавнится внутри змейки
Неверные переменные foodX и foodY

2024-05-26 18:33 UTC, alvls commented
По ЛР6

После исправления ошибки с переменными код собирается, проект запускается. Главный минус - ужасное моргание консоли.

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 7,8
Качество   проектирования: | 3,5
Качество   кода: | 3,2
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 14,5

2024-05-26 18:33 UTC, merged