task 3
alvls/mp1-2024-1 pull request #23
Opened 2024-03-17 09:59 UTC by Andrew-8705

2024-03-31 10:39 UTC, Andrew-8705 commented
[input.txt](https://github.com/alvls/mp1-2024-1/files/14815075/input.txt)
[output.txt](https://github.com/alvls/mp1-2024-1/files/14815076/output.txt)

2024-04-22 16:57 UTC, Andrew-8705 commented
Изменён способ управления экземпляром ProcessingCenter в классе Bankomat, перейдя от прямого использования к использованию указателя

2024-05-21 12:18 UTC, alvls requested changes

2024-05-21 12:18 UTC, alvls commented on baldin_al/task3/TextEditor.cpp
> +    input_str = str;
Реализация неверная. Требовалось ограничить вводимую пользователем строку установленным числом символов. А у вас можно ввести сколько угодно символов. Введенная строка, конечно, обрезается, но этого недостаточно. Нужно переделать.

2024-05-21 12:29 UTC, alvls requested changes

2024-05-21 12:29 UTC, alvls commented on baldin_al/task4/Movie.cpp
> +		if (movie == lm) {
Контейнер set хранит данные упорядоченно (по определенному вами оператору сравнения). Использовать в нем для поиска полный перебор там, где можно искать быстрее, - неверная идея.

2024-05-21 12:29 UTC, alvls commented on baldin_al/task4/Movie.cpp
> +			return movie;
См. комментарий выше.

2024-05-21 12:39 UTC, alvls requested changes

2024-05-21 12:39 UTC, alvls commented on baldin_al/task5/Bankomat.cpp
> +	clients[card_number] = Client(f_name, l_name, m_name, sum, pin_code);
Использовать номер карты в качестве ключа - правильно, но не хранить его в данных клиента - неправильно. Получается, что клиент не знает номер своей карты, - так не бывает :).

2024-05-21 13:49 UTC, Andrew-8705 commented on baldin_al/task4/Movie.cpp
> +		if (movie == lm) {
После добавления нового фильма придётся каждый раз сортировать тот же самый вектор, что будет занимать n*log(n) (в ТЗ сказано, что фильмы должны храниться упорядоченно по названию и годам). А set, в свою очередь, будет делать это автоматически за log(n). Также использование set убирает дополнительную проверку при добавлении на существование уже такого фильма. Хотя, возможно, set проигрывает в памяти для поддержания порядка и уникальности. 
И как можно искать быстрее? С помощью бин поиска?

2024-05-21 13:56 UTC, alvls commented on baldin_al/task4/Movie.cpp
> +		if (movie == lm) {
Я не призываю отказаться от set. Нужно для поиска не обходить контейнер, а использовать возможности set по поиску - там и будет время порядка log(n).

2024-05-22 09:48 UTC, alvls commented
По ЛР3

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество   кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2024-05-22 09:50 UTC, alvls commented
По ЛР4

В методе findMovieByTitleAndYear также можно использовать метод из set для поиска.

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 3,8
Качество   проектирования: | 2,0
Качество   кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 7,8

2024-05-22 09:52 UTC, alvls commented
По ЛР5

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 5,0
Качество   проектирования: | 2,5
Качество   кода: | 2,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 10,0

2024-05-27 17:04 UTC, alvls commented
По ЛР6

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 8,0
Качество   проектирования: | 3,5
Качество   кода: | 3,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 15,0

2024-05-27 17:05 UTC, merged