task 3 done
alvls/mp1-2024-1 pull request #24
Opened 2024-03-17 14:44 UTC by smallAbyss

2024-05-18 19:09 UTC, smallAbyss commented
task 6: fixed getting fio - это task5, только сейчас увидел, а как поменять название коммита не нашёл (если такое вообще возможно)

2024-05-21 14:15 UTC, alvls commented
По ЛР3

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2024-05-21 14:27 UTC, alvls commented on Luzan_EA/task4/task4.cpp
> +	vector <Tpair> singersIDList;
Поясните смысл ID для песен.

2024-05-21 14:28 UTC, alvls requested changes

2024-05-21 14:28 UTC, alvls commented on Luzan_EA/task4/task4.cpp
> +		}
Песни храняться упорядоченно, а ищите вы полным перебором. Непорядок...

2024-05-21 14:29 UTC, alvls requested changes

2024-05-21 14:29 UTC, alvls commented on Luzan_EA/task4/task4.vcxproj
> +    <ClCompile Include="error.cpp" />
Лишний файл в проекте - удалите.

2024-05-21 14:29 UTC, alvls commented on Luzan_EA/task4/task4.vcxproj
> +    <ClCompile Include="test.cpp" />
Лишний файл в проекте - удалите.

2024-05-21 14:40 UTC, alvls requested changes

2024-05-21 14:40 UTC, alvls commented on Luzan_EA/task5/task5.vcxproj
> +    <ClInclude Include="Header2.h" />
В проекте лишние файлы - удалите

2024-05-21 14:41 UTC, alvls commented
По ЛР4 исправьте замечания - см. выше.
По ЛР5 все отлично. Удалите лишние файлы из проекта, приму работу.

2024-05-22 22:41 UTC, smallAbyss commented on Luzan_EA/task4/task4.cpp
> +		}
Понял, переделал на бинарный поиск

2024-05-22 22:41 UTC, smallAbyss commented on Luzan_EA/task4/task4.vcxproj
> +    <ClCompile Include="error.cpp" />
Сделано

2024-05-22 22:41 UTC, smallAbyss commented on Luzan_EA/task4/task4.vcxproj
> +    <ClCompile Include="test.cpp" />
Сделано

2024-05-22 22:42 UTC, smallAbyss commented on Luzan_EA/task5/task5.vcxproj
> +    <ClInclude Include="Header2.h" />
Сделано

2024-05-22 22:58 UTC, smallAbyss commented on Luzan_EA/task4/task4.cpp
> +	vector <Tpair> singersIDList;
Если вы про 123 строку, то это ID не песни, а исполнителя. Я предположил, что количество исполнителей будет сильно меньше, поэтому при поиске песни вместо сравнения строк-имён будет немного быстрее сравнивать их ID, который будет даваться на этапе добавления песни
Но с введением бинарного поиска, который ищет сначала по названию (тк песни в первую очередь отсортированы по нему), а потом по исполнителю, это идея, скорее всего, потеряет смысл

А вот причина, по которой этот вектор хранит именно связки ID-Name, а не просто имена - это моя невнимательность. ID - это номер элемента в массиве, так что TPair можно заменить на string и далее внутри других методов заменить присваивание ID на присваивание номера элемента

2024-05-23 08:14 UTC, alvls commented
По ЛР5 я не заметил при прошлом просмотре один странный момент. У вас Касса включает в себя ГЖД, причем столько экземпляров, сколько дней. То есть будут 30 раз скопированы все поезда - так, конечно, не должно быть. Материальные объекты сами по себе, а расписание само по себе. Поэтому баллы такие.

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 5,0
Качество   проектирования: | 1,5
Качество   кода: | 2,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 9,0

2024-05-23 08:16 UTC, alvls commented
По ЛР4

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество   кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2024-05-27 17:30 UTC, alvls commented
По ЛР6

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 8,0
Качество   проектирования: | 3,5
Качество   кода: | 3,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 15,0

2024-05-27 17:30 UTC, merged