task3 completed
alvls/mp1-2024-1 pull request #25
Opened 2024-03-17 17:06 UTC by fartekool

2024-05-22 11:09 UTC, alvls requested changes

2024-05-22 11:09 UTC, alvls commented on levonychev_ia/task4/Source.cpp
> +		}
Контакты хранятся упорядоченно. А ищите вы перебором. Непорядок...

2024-05-22 11:10 UTC, alvls commented
По ЛР3

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество   кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2024-05-22 11:12 UTC, alvls commented
По ЛР4

Последний коммит на два дня позже срока. На первый раз штрафовать за опоздание не стал.

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 3,7
Качество   проектирования: | 2,0
Качество   кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 7,7

2024-05-22 11:25 UTC, alvls commented
По ЛР5

С точки зрения функциональности ваш код делает то, что требовалось. Но взаимодействие классов у вас спроектировано неверно.
1. Касса агрегирует кинотеатр. В реальности скорее наоборот. Более того, обычно в кинотеатре касса не одна.
2. Кинотеарт агрегирует залы - это нормально, но те же залы агрегированы у вас в MovieSession, т.е. каждый зал существует в двух копиях.
3. MovieSession не может содержать в себе зал.

С учетом штрафа за просрочку итог такой.

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 5,0
Качество   проектирования: | 1,5
Качество   кода: | 2,5
Бонус: | 0,0
Штраф: | 0,5
__Итого:__ | 8,5

2024-05-27 17:39 UTC, alvls commented
Вот так у меня выглядит поле в ЛР6

![изображение](https://github.com/alvls/mp1-2024-1/assets/5449780/59aa7cf8-6ffe-42c9-88f6-67918db45097)

2024-05-27 18:07 UTC, fartekool commented
Странно, у меня все хорошо. Может из-за раскраски поля?
![photo_2024-05-24_21-07-53](https://github.com/alvls/mp1-2024-1/assets/144248342/056225af-8252-48c3-ae96-2f43f03cf41d)

2024-05-27 18:12 UTC, alvls commented
Может быть. Попробуйте выложить вариант без раскраски.

2024-05-27 18:16 UTC, fartekool commented
Изменил.

2024-05-27 18:17 UTC, fartekool commented
Сейчас выглядит вот так.
![photo_2024-05-27_21-17-01](https://github.com/alvls/mp1-2024-1/assets/144248342/ec32d5f1-9d7b-4982-b1b8-42deb314fb3a)

2024-05-27 18:27 UTC, alvls commented
По ЛР6

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 8,0
Качество   проектирования: | 3,5
Качество   кода: | 3,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 15,0

2024-05-27 18:28 UTC, merged