Сделано задание №3
alvls/mp1-2024-1 pull request #29
Opened 2024-03-18 17:37 UTC by LeoGNZV

2024-05-23 11:14 UTC, alvls commented
По ЛР3

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество   кода: | 2,0
Бонус: | 0,1
Штраф: | 0,0
__Итого:__ | 8,1

Бонус за реализацию перевыделения памяти.

2024-05-23 11:19 UTC, alvls commented on gonozov_la/task4/Source.cpp
> +		return data;
Идея со сверткой даты хороша, но вернуть дату пользователю нужно бы в нормальном виде.

2024-05-23 11:21 UTC, alvls commented
По ЛР4

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 1,9
Качество   кода: | 2,0
Бонус: | 0,1
Штраф: | 0,0
__Итого:__ | 8,0

2024-05-23 12:46 UTC, alvls requested changes

2024-05-23 12:46 UTC, alvls commented on gonozov_la/task5/Source.cpp
> +	Processing_center proc_center;
Процессинговый центр не может принадлежать депозиту. По этой же причине этот класс не должен быть вложен в класс Депозит.

2024-05-23 12:46 UTC, alvls commented on gonozov_la/task5/Source.cpp
> +			cout << "����������� �� ����������� �������" << endl;
Методы класса не должны работать с консолью. Нужно возвращать требуемые результаты, а не выводить на экран.

2024-05-23 12:46 UTC, alvls commented on gonozov_la/task5/Source.cpp
> +	string* salary_account = new string[10];
Здесь и ниже, почему 10? Почему "магическая константа" в коде?

2024-05-23 12:46 UTC, alvls commented
По ЛР5 есть замечания. Исправьте.

2024-05-23 14:01 UTC, LeoGNZV commented on gonozov_la/task5/Source.cpp
> +			cout << "����������� �� ����������� �������" << endl;
Здравствуйте, это также нужно исправить в check_status_deposit, где я вывожу в консоль состояние депозита (дата внесения, процент, количество месяцев и т.д.), или же это касается только метода "авторизация"?

2024-05-23 14:03 UTC, LeoGNZV commented on gonozov_la/task5/Source.cpp
> +	string* salary_account = new string[10];
Я хотел использовать расширение динамического массива, когда место заканчивается. Это неправильный подход, и мне его нужно менять?

2024-05-23 14:51 UTC, alvls commented on gonozov_la/task5/Source.cpp
> +			cout << "����������� �� ����������� �������" << endl;
И там тоже исправить.

2024-05-23 14:52 UTC, alvls commented on gonozov_la/task5/Source.cpp
> +	string* salary_account = new string[10];
Это правильный подход, но даже в этом случае константы нужно вводить именованные, а не "зашивать" их в код.

2024-05-23 18:50 UTC, LeoGNZV commented
Надеюсь, что правильно понял то, что вы имели в виду, прошу прощения, если это не так

2024-05-24 17:40 UTC, alvls commented
Стало лучше, но не до конца.

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 5,0
Качество   проектирования: | 2,0
Качество   кода: | 2,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 9,5

2024-05-24 18:17 UTC, alvls commented
По ЛР6

__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 8,0
Качество   проектирования: | 3,5
Качество   кода: | 3,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 15,0

2024-05-25 15:56 UTC, merged