task 1
alvls/mp1-2024-1 pull request #8
Opened 2024-02-24 20:06 UTC by Andrew-8705

2024-03-06 19:59 UTC, alvls requested changes

2024-03-06 19:59 UTC, alvls commented on baldin_al/task1/Source.cpp
> +	int sec;
Почему тип знаковый?

2024-03-06 19:59 UTC, alvls commented on baldin_al/task1/Source.cpp
> +			cout << "Invalid time format. Time was automatically set to 00:00:00" << '\n';
Не нужно ничего выводить на консоль. Ее может не быть.

2024-03-06 19:59 UTC, alvls commented on baldin_al/task1/Source.cpp
> +	void getDiff(const Time& t)
Разница между временами это тоже время. Исправьте метод

2024-03-06 20:01 UTC, alvls requested changes

2024-03-06 20:01 UTC, alvls commented on baldin_al/task2/Source.cpp
> +	Matrix(int size_ = 0) { // ����������� ��� ������� ������� ������� ��������
Почему 0 по умолчанию? Таких матриц не бывает.

2024-03-06 22:25 UTC, Andrew-8705 commented
Исправил

2024-03-07 06:47 UTC, alvls commented
Замечание про вывод на консоль нужно исправить везде

2024-03-10 13:04 UTC, alvls commented
По заданию 1.

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2024-03-10 13:05 UTC, alvls commented
По заданию 2.

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,2
Штраф: | 0,0
__Итого:__ | 6,2

2024-03-10 13:06 UTC, merged